# This is a GitHub Actions workflow file for continuous integration (CI) of a Node.js project.
# It runs on pushes and pull requests to the 'main' branch, testing against multiple Node.js versions.

# Name of the workflow
name: Node.js CI

# Trigger workflow on push or pull request to the 'main' branch
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# Workflow jobs
jobs:
  build:
    # Use the latest Ubuntu runner
    runs-on: ubuntu-latest

    # Define Node.js versions to test against
    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # Step 3: Cache Node Modules
      - name: Cache Node Modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # Step 4: Install dependencies using clean install
      - name: Install dependencies
        run: npm install

      # Step 5: Build the project (if applicable)
      - name: Build project
        run: npm run build --if-present

      # Step 6: Run tests
      - name: Run tests
        run: npm test

      # Step 7: Run Linter
      - name: Run ESLint
        run: npx eslint .