# This is a GitHub Actions workflow file for continuous integration (CI) of a Node.js project.
# It runs on pushes and pull requests to the 'main' branch, testing against multiple Node.js versions.

# Name of the workflow
name: Node.js CI

# Trigger workflow on push or pull request to the 'main' branch
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# Workflow jobs
jobs:
  build:
    # Use the latest Ubuntu runner
    runs-on: ubuntu-latest

    # Define Node.js versions to test against
    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # Step 3: Install dependencies using clean install
      - name: Install dependencies
        run: npm ci

      # Step 4: Build the project (if applicable)
      - name: Build project
        run: npm run build --if-present

      # Step 5: Run tests
      - name: Run tests
        run: npm test
