name: Create Release

on:
  push:
    tags:
      - '*'  # This triggers the workflow when ANY tag is pushed.

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        # Checks out the code for the commit that the tag points to.

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
        # Creates a release using the tag name (e.g., v1.0.0)
